apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartKind: pages
    chartRepository: https://github.com/jenkins-x-bdd/repo.git
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
    owner: keskad
    repository: jx3-k3s-test-clear
  - key: staging
  ingress:
    domain: k3s-aws.keskad.pl
    ignoreLoadBalancer: true
    kind: ingress
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: keskad
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
